---
ruby_version: 2.3.7
node_version: 8.9.1

# Directories to be created in home folder
home_directories:
  - Repository
  - DockerApps
  - .bin

homebrew_upgrade_all_packages: false

homebrew_installed_packages:
  - autoconf
  - git
  - httpie
  - htop
  - imagemagick
  - tree
  - mcrypt
  - nvm
  - openssl
  - rbenv
  - readline
  - ruby-build
  - wget
  - libpq
  - zsh
  - ctop
  - tmux

homebrew_uninstalled_packages: []

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_apps:
  - chromedriver
  - firefox
  - google-chrome
  - handbrake
  - slack
  - visual-studio-code
  - postman
  - keepassxc
  - rectangle
  - vlc
  - iterm2
  - font-meslo-lg-nerd-font # Font used by powerlevel10k

homebrew_cask_uninstalled_apps: []
