---
ruby_version: 2.3.7
node_version: 8.9.1

homebrew_upgrade_all_packages: no

homebrew_installed_packages:
  - autoconf
  - git
  - httpie
  - imagemagick
  - mcrypt
  - nvm
  - openssl
  - postgresql@9.4
  - rbenv
  - readline
  - redis@3.2
  - ruby-build
  - wget
  - yarn

homebrew_uninstalled_packages: []

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/services

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - firefox
  - google-chrome
  - handbrake
  - java8
  - slack
  - sublime-text
  - visual-studio-code

homebrew_cask_uninstalled_apps: []
