---
- set_fact: bazel_found=False expected_version=False remove_current_version=False

- name: "Check bazel version: {{bazel_version}}" 
  command: /usr/local/bin/bazel version
  register: command_result
  ignore_errors: True

- set_fact: bazel_found=True
  when: command_result is succeeded

- set_fact: expected_version="{{ command_result.stdout.find(bazel_version) != -1 }}"
  when: bazel_found
- set_fact: remove_current_version="{{ (bazel_found and not expected_version) }}"

- name: Removing current bazel version
  command: /usr/local/bin/brew remove bazel
  when: remove_current_version

- name: "Installing bazel version: {{bazel_version}}"
  command: "/usr/local/bin/brew install {{ bazel_formula_url }}"
  when: not bazel_found or not expected_version