---
- set_fact: elasticsearch_found=False expected_version=False remove_current_version=False

- name: "Check elasticsearch version: {{elasticsearch_version}}" 
  command: /usr/local/bin/brew ls elasticsearch
  register: command_result
  ignore_errors: True

- set_fact: elasticsearch_found=True
  when: command_result is succeeded

- set_fact: expected_version="{{ command_result.stdout.find(elasticsearch_version) != -1 }}"
  when: elasticsearch_found

- set_fact: remove_current_version="{{ (elasticsearch_found and not expected_version) }}"

- name: "Stopping current elasticsearch service"
  command: "/usr/local/bin/brew services start elasticsearch"
  when: remove_current_version

- name: Removing current elasticsearch version
  command: /usr/local/bin/brew remove elasticsearch
  when: remove_current_version

- name: Copy elasticsearch brew formula to tmp dir
  template:
    src: templates/Formula/elasticsearch.rb.j2
    dest: /tmp/elasticsearch.rb
  when: not elasticsearch_found

- name: "Installing elasticsearch version: {{elasticsearch_version}}"
  command: "/usr/local/bin/brew install /tmp/elasticsearch.rb"
  when: not elasticsearch_found or not expected_version

- name: Create elasticsearch.yml
  copy:
    content: ""
    dest: "/usr/local/etc/elasticsearch/elasticsearch.yml"
    force: no 

- name: "Ensure elasticsearch.yml has config lines"
  lineinfile: 
    dest: "{{ item.dest }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { dest: "/usr/local/etc/elasticsearch/elasticsearch.yml", line: 'http.cors.allow-origin: "*"'}
    - { dest: "/usr/local/etc/elasticsearch/elasticsearch.yml", line: 'http.cors.enabled: true'}
    - { dest: "/usr/local/etc/elasticsearch/elasticsearch.yml", line: 'script.inline: true'}

- name: "Starting elasticsearch service"
  command: "/usr/local/bin/brew services start elasticsearch"