---
- name: "Check ruby version: {{ ruby_version }}" 
  command: "/usr/local/bin/rbenv versions"
  register: command_result

- set_fact: version_installed="{{ command_result.stdout.find(ruby_version) != -1 }}"

- name: "Installing ruby version: {{ ruby_version }}" 
  command: "/usr/local/bin/rbenv install {{ ruby_version }}"
  when: not version_installed