---
- name: Update .zshrc adding rbenv init
  lineinfile:
    path: "{{ansible_env.HOME}}/.zshrc"
    line: eval "$(rbenv init -)"

- include_tasks: install_version.yml
  vars:
    ruby_version: "{{item}}"
  with_items: "{{ruby_versions_install}}"

- name: "Check global ruby version"
  command: "/usr/local/bin/rbenv version"
  register: global_version

- set_fact: global_version_different="{{ global_version.stdout.find(default_ruby_version) == -1 }}"

- name: "Set global ruby version: {{ default_ruby_version }}"
  command: "/usr/local/bin/rbenv global {{ default_ruby_version }}"
  when: global_version_different

- name: Add bundle config libpq before installing pg gem
  ansible.builtin.shell: "bundle config --global build.pg --with-opt-dir=\"/usr/local/opt/libpq\""

- name: Copy .railsrc file
  template:
    src: railsrc.j2
    dest: "{{ansible_env.HOME}}/.railsrc"

- name: Copy default rails_template file
  copy:
    src: "rails_template.rb"
    dest: "{{ansible_env.HOME}}/.rails_template.rb"